name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Replace with the desired .NET SDK version
      - name: Analyze with SonarScanner for MSBuild
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"BackEnd" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build ./sourcecode/BackEnd/JWTToken/JWTToken.csproj
          dotnet build ./sourcecode/BackEnd/AzureFunctionApp/AzureFunctionApp.csproj
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"