name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Analyze with SonarScanner for .NET
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          docker run --rm \
            -v "${PWD}:/usr/src" \
            -v "/var/run/docker.sock:/var/run/docker.sock" \
            -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
            -e SONAR_LOGIN=${{ secrets.SONAR_TOKEN_BACKEND }} \
            sonarsource/dotnet-sonarscanner \
            begin /k:"BackEnd" /d:sonar.login="$SONAR_LOGIN" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.sources=./sourcecode/BackEnd
      - name: Build and analyze with dotnet build
        run: |
          cd ./sourcecode/BackEnd
          for project in $(find . -name '*.csproj'); do
            dotnet build "$project"
          done
      - name: Finalize SonarScanner analysis
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          docker run --rm \
            -v "${PWD}:/usr/src" \
            -v "/var/run/docker.sock:/var/run/docker.sock" \
            -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
            -e SONAR_LOGIN=${{ secrets.SONAR_TOKEN_BACKEND }} \
            sonarsource/dotnet-sonarscanner \
            end /d:sonar.login="$SONAR_LOGIN" /d:sonar.host.url="$SONAR_HOST_URL"
