name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          curl -LsS "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip" -o sonar-scanner.zip
          unzip sonar-scanner.zip -d ./.sonar/scanner
      - name: Build and analyze
        run: |
          ./.sonar/scanner/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner \
            -Dsonar.projectKey=BackEnd \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN_BACKEND }}
          cd ./sourcecode/BackEnd
          dotnet build AzureFunctionApp
          dotnet build JWTToken
          cd ../..
          ./.sonar/scanner/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner -X \
            -Dsonar.login=${{ secrets.SONAR_TOKEN_BACKEND }}