name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Analyze with SonarScanner for .NET
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          docker run --rm \
            -v "${PWD}:/usr/src" \
            -v "/var/run/docker.sock:/var/run/docker.sock" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=BackEnd \
            -Dsonar.sources=./sourcecode/BackEnd/AzureFunctionApp,./sourcecode/BackEnd/jwt \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN_BACKEND }}
      - name: Build and analyze with dotnet build
        run: |
          cd ./sourcecode/BackEnd
          for project in $(find . -name '*.csproj'); do
            dotnet build "$project"
          done