name: Build

on:
  push:
    branches:
      - main

  pull_request:  
    types:
      - opened
      - synchronize  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Replace with the desired .NET SDK version
      - name: Create analysis directory
        run: mkdir analysis
      - name: Copy project files to analysis directory
        run: |
          find sourcecode/BackEnd -type d -maxdepth 1 -exec cp -R {} analysis \;
      - name: Analyze with SonarScanner for MSBuild
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        working-directory: ./analysis
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"BackEnd" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN_BACKEND }}"
          for project in $(find . -name '*.csproj'); do
            dotnet build "$project"
          done
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN_BACKEND }}"